{-# LANGUAGE OverloadedStrings #-}

-- | Idiomatic Haskell wrapper around the official C webview API.
--
-- This module presents the API in @IO (Either 'WebviewError' a)@ form and uses
-- 'Text' for all string parameters. The raw FFI bindings generated by
-- @hs-bindgen@ live in "WebView.Raw", "WebView.Raw.Safe" and
-- "WebView.Raw.Unsafe" and remain accessible for power users.
module WebView
  ( -- * Handle
    WebView
  , WebViewHint (..)
  , NativeHandleKind (..)
  , Version (..)

    -- * Lifecycle
  , create
  , destroy
  , run
  , terminate
  , withWebView

    -- * Threading
  , dispatch

    -- * Native handles
  , getWindow
  , getNativeHandle

    -- * Window properties
  , setTitle
  , setSize

    -- * Content
  , navigate
  , setHtml
  , reload

    -- * JavaScript
  , initJs
  , evalJs

    -- * JS <-> Haskell binding
  , bind
  , unbind
  , webviewReturn

    -- * Library info
  , version

    -- * Errors
  , WebviewError (..)
  ) where

import Control.Exception (bracket)
import Data.Text (Text)
import qualified Data.Text as T
import Data.Word (Word32)
import Foreign.C.String (peekCString, withCString)
import Foreign.C.Types (CChar)
import Foreign.Ptr (FunPtr, Ptr, castFunPtr, castPtr, nullPtr)
import Foreign.Storable (peek)
import qualified HsBindgen.Runtime.PtrConst as PtrConst

import WebView.Error (WebviewError (..), toResult)
import WebView.Internal (WebView)
import qualified WebView.Raw as Raw
import qualified WebView.Raw.Safe as Safe
import qualified WebView.Raw.Unsafe as Unsafe

-- | Window sizing hints understood by webview.
data WebViewHint
  = HintNone
  | HintMin
  | HintMax
  | HintFixed
  deriving (Eq, Show)

-- | Kinds of native handle exposed by 'getNativeHandle'.
data NativeHandleKind
  = UIWindow
  | UIWidget
  | BrowserController
  deriving (Eq, Show)

-- | SemVer-style version triple as returned by 'version'.
data Version = Version
  { versionMajor :: !Word32
  , versionMinor :: !Word32
  , versionPatch :: !Word32
  }
  deriving (Eq, Show)

hintToRaw :: WebViewHint -> Raw.Webview_hint_t
hintToRaw HintNone  = Raw.WEBVIEW_HINT_NONE
hintToRaw HintMin   = Raw.WEBVIEW_HINT_MIN
hintToRaw HintMax   = Raw.WEBVIEW_HINT_MAX
hintToRaw HintFixed = Raw.WEBVIEW_HINT_FIXED

kindToRaw :: NativeHandleKind -> Raw.Webview_native_handle_kind_t
kindToRaw UIWindow          = Raw.WEBVIEW_NATIVE_HANDLE_KIND_UI_WINDOW
kindToRaw UIWidget          = Raw.WEBVIEW_NATIVE_HANDLE_KIND_UI_WIDGET
kindToRaw BrowserController = Raw.WEBVIEW_NATIVE_HANDLE_KIND_BROWSER_CONTROLLER

withText :: Text -> (PtrConst.PtrConst CChar -> IO a) -> IO a
withText t k = withCString (T.unpack t) (k . PtrConst.unsafeFromPtr)

-- | Create a new webview instance. Pass 'True' to enable developer tools when
-- supported by the backend.
create :: Bool -> IO WebView
create debug = Unsafe.webview_create (if debug then 1 else 0) nullPtr

-- | Destroy the webview and close its native window.
destroy :: WebView -> IO (Either WebviewError ())
destroy wv = toResult <$> Unsafe.webview_destroy wv

-- | Enter the GUI main loop. Blocks until 'terminate' is called.
--
-- This binding is marked @safe@ at the FFI level so other Haskell threads can
-- continue running while the GUI loop blocks.
run :: WebView -> IO (Either WebviewError ())
run wv = toResult <$> Safe.webview_run wv

-- | Stop the main loop. Safe to call from another thread.
terminate :: WebView -> IO (Either WebviewError ())
terminate wv = toResult <$> Unsafe.webview_terminate wv

-- | Bracket 'create' / 'destroy'. The 'Either' result of 'destroy' is
-- discarded since exceptions cannot be raised during bracket cleanup safely.
withWebView :: Bool -> (WebView -> IO a) -> IO a
withWebView debug = bracket (create debug) (\wv -> destroy wv >> pure ())

-- | Schedule a function to run on the GUI thread. Useful for safe interaction
-- with the webview from background threads.
--
-- The 'FunPtr' allocated for the closure is leaked. Use sparingly.
dispatch :: WebView -> (WebView -> IO ()) -> IO (Either WebviewError ())
dispatch wv k = do
  fp <- mkDispatchCallback $ \rawWv _ -> k (Raw.Webview_t (castPtr rawWv))
  toResult <$> Unsafe.webview_dispatch wv (castFunPtr fp) nullPtr

-- | Return the native top-level window handle.
getWindow :: WebView -> IO (Ptr ())
getWindow wv = castPtr <$> Unsafe.webview_get_window wv

-- | Return a native handle of the requested 'NativeHandleKind'.
getNativeHandle :: WebView -> NativeHandleKind -> IO (Ptr ())
getNativeHandle wv k = castPtr <$> Unsafe.webview_get_native_handle wv (kindToRaw k)

-- | Update the native window title.
setTitle :: WebView -> Text -> IO (Either WebviewError ())
setTitle wv t = withText t $ \cstr ->
  toResult <$> Unsafe.webview_set_title wv cstr

-- | Update the native window size.
setSize :: WebView -> Int -> Int -> WebViewHint -> IO (Either WebviewError ())
setSize wv w h hint =
  toResult <$> Unsafe.webview_set_size wv (fromIntegral w) (fromIntegral h) (hintToRaw hint)

-- | Navigate to a URL (may be a properly encoded data URI).
navigate :: WebView -> Text -> IO (Either WebviewError ())
navigate wv url = withText url $ \cstr ->
  toResult <$> Unsafe.webview_navigate wv cstr

-- | Load inline HTML into the webview.
setHtml :: WebView -> Text -> IO (Either WebviewError ())
setHtml wv html = withText html $ \cstr ->
  toResult <$> Unsafe.webview_set_html wv cstr

-- | Reload the current page by evaluating @window.location.reload()@.
reload :: WebView -> IO (Either WebviewError ())
reload wv = evalJs wv "window.location.reload();"

-- | Inject JavaScript to run on every page load (before @window.onload@).
initJs :: WebView -> Text -> IO (Either WebviewError ())
initJs wv js = withText js $ \cstr ->
  toResult <$> Unsafe.webview_init wv cstr

-- | Evaluate arbitrary JavaScript in the page. Use 'bind' if you need a return
-- value back on the Haskell side.
evalJs :: WebView -> Text -> IO (Either WebviewError ())
evalJs wv js = withText js $ \cstr ->
  toResult <$> Unsafe.webview_eval wv cstr

-- | Bind a global JavaScript function. The callback receives the request ID
-- (use it with 'webviewReturn') and a JSON-encoded argument array.
--
-- The 'FunPtr' allocated for the callback is leaked for the lifetime of the
-- 'WebView'; pair every 'bind' with 'unbind' if you intend to rebind names
-- and worry about memory.
bind :: WebView -> Text -> (Text -> Text -> IO ()) -> IO (Either WebviewError ())
bind wv name k = withText name $ \cstr -> do
  fp <- mkBindCallback $ \idPtr reqPtr _ -> do
    idText  <- T.pack <$> peekCString idPtr
    reqText <- T.pack <$> peekCString reqPtr
    k idText reqText
  toResult <$> Unsafe.webview_bind wv cstr (castFunPtr fp) nullPtr

-- | Remove a binding created with 'bind'.
unbind :: WebView -> Text -> IO (Either WebviewError ())
unbind wv name = withText name $ \cstr ->
  toResult <$> Unsafe.webview_unbind wv cstr

-- | Respond to a binding call from JS. Pass status @0@ for success; any other
-- status indicates an error to the JS side. The result string must be a valid
-- JSON value or empty for @undefined@.
webviewReturn :: WebView -> Text -> Int -> Text -> IO (Either WebviewError ())
webviewReturn wv idText status result =
  withText idText $ \idPtr ->
    withText result $ \resPtr ->
      toResult <$> Unsafe.webview_return wv idPtr (fromIntegral status) resPtr

-- | Library version information (major.minor.patch).
version :: IO Version
version = do
  infoPtrC <- Unsafe.webview_version
  -- @struct webview_version_t@ is the first field at offset 0, so we can peek
  -- it directly from the start of the info struct and skip the trailing
  -- fixed-size string arrays.
  Raw.Webview_version_t mj mn pa <- peek (castPtr (PtrConst.unsafeToPtr infoPtrC))
  pure $ Version (fromIntegral mj) (fromIntegral mn) (fromIntegral pa)

-- Wrapper imports for the two callback types used by dispatch/bind. We use
-- the FFI-friendly raw pointer types and cast at the call site, because GHC
-- only allows fully marshallable types in @foreign import \"wrapper\"@.

foreign import ccall "wrapper"
  mkDispatchCallback
    :: (Ptr () -> Ptr () -> IO ())
    -> IO (FunPtr (Ptr () -> Ptr () -> IO ()))

foreign import ccall "wrapper"
  mkBindCallback
    :: (Ptr CChar -> Ptr CChar -> Ptr () -> IO ())
    -> IO (FunPtr (Ptr CChar -> Ptr CChar -> Ptr () -> IO ()))
